apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: comment-commander
resources:
  - ../../base
images:
  - name: ghcr.io/magmamoose/comment-commander
    newTag: v1.10.0 # {"$imagepolicy": "flux-system:comment-commander:tag"}
